base_schedule = {
    "frank_week": {
        "Monday": [
            {"id": "Line1", "assignment": "Line", "AM": "Hemi", "PM": "Hemi"},
            {"id": "Line2", "assignment": "Line", "AM": "Iraida", "PM": "Desi"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Michelle", "PM": "Eb"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Leslie", "PM": "Pree"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Graham", "PM": "Iraida"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Pree", "PM": "Michelle"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Tim", "PM": "Frank"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Eb", "PM": "Tim"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": ""},
            {"id": "IMO", "assignment": "IMO", "AM": "Desi", "PM": "Graham"},
            {"id": "Backup", "assignment": "Backup", "AM": "Frank", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Tim", "PM": ""},
        ],
        "Tuesday": [
            {"id": "Line1", "assignment": "Line", "AM": "Tim", "PM": "Graham"},
            {"id": "Line2", "assignment": "Line", "AM": "Michelle", "PM": "Frank"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Frank", "PM": "Tim"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Desi", "PM": "Caroline"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Eb", "PM": "Hemi"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Hemi", "PM": "Desi"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Graham", "PM": "Eb"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Leslie", "PM": "Michelle"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Iraida"},
            {"id": "IMO", "assignment": "IMO", "AM": "Iraida", "PM": "Pree"},
            {"id": "Backup", "assignment": "Backup", "AM": "Pree", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Leslie", "PM": ""},
        ],
        "Wednesday": [
            {"id": "Line1", "assignment": "Line", "AM": "Eb", "PM": "Pree"},
            {"id": "Line2", "assignment": "Line", "AM": "Leslie", "PM": "Graham"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Pree", "PM": "Caroline"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Michelle", "PM": "Tim"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Frank", "PM": "Iraida"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Iraida", "PM": "Eb"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Desi", "PM": "Hemi"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Hemi", "PM": "Frank"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Desi"},
            {"id": "IMO", "assignment": "IMO", "AM": "Tim", "PM": "Michelle"},
            {"id": "Backup", "assignment": "Backup", "AM": "Graham", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Caroline", "PM": ""},
        ],
        "Thursday": [
            {"id": "Line1", "assignment": "Line", "AM": "Frank", "PM": "Iraida"},
            {"id": "Line2", "assignment": "Line", "AM": "Tim", "PM": "Hemi"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Leslie", "PM": "Desi"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Graham", "PM": "Frank"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Michelle", "PM": "Pree"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Eb", "PM": "Michelle"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Iraida", "PM": "Graham"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Pree", "PM": "Caroline"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Tim"},
            {"id": "IMO", "assignment": "IMO", "AM": "Hemi", "PM": "Eb"},
            {"id": "Backup", "assignment": "Backup", "AM": "Desi", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Eb", "PM": ""},
        ],
        "Friday": [
            {"id": "Line1", "assignment": "Line", "AM": "Michelle", "PM": "Caroline"},
            {"id": "Line2", "assignment": "Line", "AM": "Desi", "PM": "Pree"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Graham", "PM": "Hemi"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Hemi", "PM": "Eb"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Tim", "PM": "Desi"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Pree", "PM": "Frank"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Eb", "PM": "Tim"},
            {"id": "Mail1", "assignment": "Mail", "AM": "", "PM": "Graham"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Michelle"},
            {"id": "IMO", "assignment": "IMO", "AM": "Frank", "PM": "Iraida"},
            {"id": "Backup", "assignment": "Backup", "AM": "Iraida", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Frank", "PM": ""},
        ],
    },
    "lloyd_week": {
        "Monday": [
            {"id": "Line1", "assignment": "Line", "AM": "Hemi", "PM": "Hemi"},
            {"id": "Line2", "assignment": "Line", "AM": "Lloyd", "PM": "Desi"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Michelle", "PM": "Eb"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Leslie", "PM": "Pree"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Graham", "PM": "Lloyd"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Pree", "PM": "Michelle"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Tim", "PM": "Kara"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Eb", "PM": "Tim"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": ""},
            {"id": "IMO", "assignment": "IMO", "AM": "Desi", "PM": "Graham"},
            {"id": "Backup", "assignment": "Backup", "AM": "Kara", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Tim", "PM": ""},
        ],
        "Tuesday": [
            {"id": "Line1", "assignment": "Line", "AM": "Tim", "PM": "Graham"},
            {"id": "Line2", "assignment": "Line", "AM": "Michelle", "PM": "Kara"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Kara", "PM": "Tim"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Desi", "PM": "Caroline"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Eb", "PM": "Hemi"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Hemi", "PM": "Desi"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Graham", "PM": "Eb"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Leslie", "PM": "Michelle"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Lloyd"},
            {"id": "IMO", "assignment": "IMO", "AM": "Lloyd", "PM": "Pree"},
            {"id": "Backup", "assignment": "Backup", "AM": "Pree", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Leslie", "PM": ""},
        ],
        "Wednesday": [
            {"id": "Line1", "assignment": "Line", "AM": "Eb", "PM": "Pree"},
            {"id": "Line2", "assignment": "Line", "AM": "Leslie", "PM": "Graham"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Pree", "PM": "Caroline"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Michelle", "PM": "Tim"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Kara", "PM": "Lloyd"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Lloyd", "PM": "Eb"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Desi", "PM": "Hemi"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Hemi", "PM": "Kara"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Desi"},
            {"id": "IMO", "assignment": "IMO", "AM": "Tim", "PM": "Michelle"},
            {"id": "Backup", "assignment": "Backup", "AM": "Graham", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Caroline", "PM": ""},
        ],
        "Thursday": [
            {"id": "Line1", "assignment": "Line", "AM": "Kara", "PM": "Lloyd"},
            {"id": "Line2", "assignment": "Line", "AM": "Tim", "PM": "Hemi"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Leslie", "PM": "Desi"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Graham", "PM": "Kara"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Michelle", "PM": "Pree"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Eb", "PM": "Michelle"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Lloyd", "PM": "Graham"},
            {"id": "Mail1", "assignment": "Mail", "AM": "Pree", "PM": "Caroline"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Tim"},
            {"id": "IMO", "assignment": "IMO", "AM": "Hemi", "PM": "Eb"},
            {"id": "Backup", "assignment": "Backup", "AM": "Desi", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Eb", "PM": ""},
        ],
        "Friday": [
            {"id": "Line1", "assignment": "Line", "AM": "Michelle", "PM": "Caroline"},
            {"id": "Line2", "assignment": "Line", "AM": "Desi", "PM": "Pree"},
            {"id": "Cage", "assignment": "Cage", "AM": "Jen", "PM": "Jen"},
            {"id": "Fee", "assignment": "Fee", "AM": "Graham", "PM": "Hemi"},
            {"id": "Phone_CCC", "assignment": "Phone/CCC", "AM": "Hemi", "PM": "Eb"},
            {"id": "OP_General", "assignment": "OP General", "AM": "Tim", "PM": "Desi"},
            {"id": "Windows1", "assignment": "Windows", "AM": "Pree", "PM": "Lloyd"},
            {"id": "Windows2", "assignment": "Windows", "AM": "Eb", "PM": "Tim"},
            {"id": "Mail1", "assignment": "Mail", "AM": "", "PM": "Graham"},
            {"id": "Mail2", "assignment": "Mail", "AM": "", "PM": "Michelle"},
            {"id": "IMO", "assignment": "IMO", "AM": "Kara", "PM": "Kara"},
            {"id": "Backup", "assignment": "Backup", "AM": "Lloyd", "PM": ""},
            {"id": "CMOP_Rejects", "assignment": "CMOP Rejects", "AM": "Kara", "PM": ""},
        ],
    }
}
